apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastfoodapi-producao-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastfoodapi-producao-deployment
  template:
    metadata:
      labels:
        app: fastfoodapi-producao-deployment
    spec:
      containers:
        - name: fastfoodapi-producao-pod
          image: rm359211/fastfood-producao-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"