version: "3.8"

volumes:
  redis_data: {}

services:
  fastfood_app:
    image: fastfood-producao-app:1
    container_name: fastfood_app
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - redis
    networks:
      - fastfood_net

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - fastfood_net

networks:
  fastfood_net:
    driver: bridge