spring:
  application:
    name: fastfood-producao
  redis:
    host: redis-0.redis.default.svc.cluster.local
    port: 6379
    timeout: 60000
    lettuce:
      shutdown-timeout: 100ms
    jedis:
      pool:
        max-active: 10
        max-idle: 5
        min-idle: 1
  cache:
    type: redis

server:
  servlet:
    context-path: /fastfood

logging:
  level:
    org.springframework.data.redis: INFO