spring:
  application:
    name: fastfood-producao
  redis:
    host: clustercfg.redis.w1u3jw.use1.cache.amazonaws.com
    port: 6379
    lettuce:
      shutdown-timeout: 100ms
    timeout: 60000
    jedis:
      pool:
        max-active: 10
        max-idle: 5
        min-idle: 1
  cache:
    type: redis

server:
  servlet:
    context-path: /fastfood

logging:
  level:
    org.springframework.data.redis: INFO