apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: default
spec:
  selector:
    app: redis  # ✅ Deve bater com o label do pod
  ports:
    - port: 6379
      targetPort: 6379
      name: redis
