apiVersion: v1
kind: Service
metadata:
  name: fastfoodapi-producao-service
spec:
  type: NodePort
  selector:
    app: fastfoodapi-producao
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001